# Generated by Django 3.1.4 on 2021-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CashierDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'cashier',
            },
        ),
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('firsttime', models.TimeField()),
                ('lasttime', models.TimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'cashierwork',
            },
        ),
    ]
